[phases.setup]
nixPkgs = ["python311", "gcc", "chromium", "chromedriver"]

[phases.install]
cmds = ["python -m venv /opt/venv", ". /opt/venv/bin/activate", "pip install -r requirements.txt"]

[phases.start]
cmd = "python app.py"
